[metadata]
name = landscapy
version = 0.1.0
description = A Python package for landscape analysis and visualization
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:

[options.packages.find]
exclude =
    tests
